---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Check if Tanium is already installed
  ansible.builtin.stat:
    path: "{{ install_directory }}"
  register: tanium_directory

- name: Install Tanium
  block:
    - name: Grab Tanium system package and initialization file from S3
      amazon.aws.aws_s3:
        bucket: "{{ third_party_bucket_name }}"
        object: "{{ item }}"
        dest: /tmp/{{ item }}
        mode: get
      become: no
      delegate_to: localhost
      loop:
        - "{{ package_object_name }}"
        - "{{ initialization_file_object_name }}"

    - name: Copy the Tanium system package
      ansible.builtin.copy:
        dest: /tmp/{{ package_object_name }}
        mode: 0700
        src: /tmp/{{ package_object_name }}

    - name: Load tasks file based on the OS type
      ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}.yml"
          paths:
            - "{{ role_path }}/tasks"

    - name: Check the Tanium server hostname
      ansible.builtin.command: "{{ install_directory }}/TaniumClient config get ServerName"
      changed_when: false
      failed_when: get_tanium_server_name.rc != 0
      register: get_tanium_server_name

    - name: Set the Tanium server hostname
      ansible.builtin.command: "{{ install_directory }}/TaniumClient config set-string ServerName {{ server_name }}"
      changed_when: set_tanium_hostname.rc == 0
      failed_when: set_tanium_hostname.rc != 0
      register: set_tanium_hostname
      when: get_tanium_server_name.stdout != server_name

    - name: Check the Tanium server port
      ansible.builtin.command: "{{ install_directory }}/TaniumClient config get ServerPort"
      changed_when: false
      failed_when: get_tanium_server_port.rc != 0
      register: get_tanium_server_port

    - name: Set the Tanium server port
      ansible.builtin.command: "{{ install_directory }}/TaniumClient config set-number ServerPort {{ server_port }}"
      changed_when: set_tanium_server_port_cmd.rc == 0
      failed_when: set_tanium_server_port_cmd.rc != 0
      register: set_tanium_server_port_cmd
      when: get_tanium_server_port.stdout != server_port

    - name: Copy the Tanium initialization file
      ansible.builtin.copy:
        dest: "{{ install_directory }}/{{ initialization_file_object_name }}"
        mode: 0600
        src: /tmp/{{ initialization_file_object_name }}

    - name: Delete local copy of Tanium system package and initialization file
      ansible.builtin.file:
        path: /tmp/{{ item }}
        state: absent
      become: no
      delegate_to: localhost
      loop:
        - "{{ package_object_name }}"
        - "{{ initialization_file_object_name }}"

    - name: Delete remote copy of Tanium system package
      ansible.builtin.file:
        path: /tmp/{{ package_object_name }}
        state: absent

  when: not tanium_directory.stat.exists

- name: Enable the Tanium service
  ansible.builtin.service:
    enabled: yes
    name: taniumclient
